{{- if .Values.optionalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: sd-secret
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: sdsecret
type: Opaque
data:
{{ (.Files.Glob "key/*").AsSecrets | indent 2 }}
{{- end }}