{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: sd-secret
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: sdsecret
type: Opaque
data:
{{ (.Files.Glob "secrets/*").AsSecrets | indent 2 }}
{{- end -}}